// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY
export const imageMap = {
  "../assets/WoodlandImages/Level1_1.jpg": require("../assets/WoodlandImages/Level1_1.jpg"),
  "../assets/WoodlandImages/Level1_1_1.jpg": require("../assets/WoodlandImages/Level1_1_1.jpg"),
  "../assets/WoodlandImages/Level1_2_1.jpg": require("../assets/WoodlandImages/Level1_2_1.jpg"),
  "../assets/WoodlandImages/Level1_3_1.jpg": require("../assets/WoodlandImages/Level1_3_1.jpg"),
  "../assets/WoodlandImages/Level1_3_2.jpg": require("../assets/WoodlandImages/Level1_3_2.jpg"),
  "../assets/WoodlandImages/Level1_4_2.jpg": require("../assets/WoodlandImages/Level1_4_2.jpg"),
  "../assets/WoodlandImages/Level1_Entry.jpg": require("../assets/WoodlandImages/Level1_Entry.jpg"),
  "../assets/WoodlandImages/Level1_Entry_1.jpg": require("../assets/WoodlandImages/Level1_Entry_1.jpg"),
  "../assets/WoodlandImages/Level1_Outside_1.jpg": require("../assets/WoodlandImages/Level1_Outside_1.jpg"),
  "../assets/WoodlandImages/Level1_Outside_2.jpg": require("../assets/WoodlandImages/Level1_Outside_2.jpg"),
  "../assets/WoodlandImages/Level1_Outside_3.jpg": require("../assets/WoodlandImages/Level1_Outside_3.jpg"),
  "../assets/WoodlandImages/Level1_Outside_4.jpg": require("../assets/WoodlandImages/Level1_Outside_4.jpg"),
  "../assets/WoodlandImages/Level2_1.jpg": require("../assets/WoodlandImages/Level2_1.jpg"),
  "../assets/WoodlandImages/Level2_2.jpg": require("../assets/WoodlandImages/Level2_2.jpg"),
  "../assets/WoodlandImages/Level2_2_1.jpg": require("../assets/WoodlandImages/Level2_2_1.jpg"),
  "../assets/WoodlandImages/Level2_3.jpg": require("../assets/WoodlandImages/Level2_3.jpg"),
  "../assets/WoodlandImages/Level2_3_1.jpg": require("../assets/WoodlandImages/Level2_3_1.jpg"),
  "../assets/WoodlandImages/Level3_1.jpg": require("../assets/WoodlandImages/Level3_1.jpg"),
  "../assets/WoodlandImages/Level3_1_1.jpg": require("../assets/WoodlandImages/Level3_1_1.jpg"),
  "../assets/WoodlandImages/Level3_2.jpg": require("../assets/WoodlandImages/Level3_2.jpg"),
  "../assets/WoodlandImages/Level3_2_1.jpg": require("../assets/WoodlandImages/Level3_2_1.jpg"),
  "../assets/WoodlandImages/Level3_3.jpg": require("../assets/WoodlandImages/Level3_3.jpg"),
  "../assets/WoodlandImages/Level3_3_1.jpg": require("../assets/WoodlandImages/Level3_3_1.jpg"),
  "../assets/WoodlandImages/Level3_4_1.jpg": require("../assets/WoodlandImages/Level3_4_1.jpg"),
  "../assets/WoodlandImages/Level3_4_2.jpg": require("../assets/WoodlandImages/Level3_4_2.jpg"),
};
